version: '3'
services:
  mqtt-broker:
    image: mosquitto-broker
    build:
      dockerfile: Dockerfile.mqtt
      context: .
    ports:
      - 1883:1883
  zookeeper:
    image: rpi-zookeeper
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        KAFKA_VERSION: 2.1.0    
    ports:
      - 2181:2181  
  kafka:
    image: rpi-kafka
    build:
      dockerfile: Dockerfile.kafka
      context: .
      args:
        KAFKA_VERSION: 2.1.0
    ports:
      - 9092:9092
    depends_on:
      - "zookeeper"    
  mqtt-kafka-producer:
    image: mqtt-kafka
    build:
      dockerfile: Dockerfile.mqtt-kafka
      context: .
    depends_on:
      - "kafka"  
