version: '3'
services:
  mqtt-broker:
    image: mosquitto-broker
    build:
      dockerfile: Dockerfile.mqtt
      context: .
    ports:
      - 1883:1883
  zookeeper:
    image: rpi-kafka
    build:
      dockerfile: Dockerfile.kafka
      context: .
      args:
        KAFKA_VERSION: 2.1.0    
    ports:
      - 2181:2181  
  kafka:
    image: rpi-kafka
    build:
      dockerfile: Dockerfile.kafka
      context: .
      args:
        KAFKA_VERSION: 2.1.0
    ports:
      - 9092:9092

